annotations:
  meta.x-helm.dev/editor: '{"group":"openviz.dev","version":"v1alpha1","resource":"grafanadatasources"}'
apiVersion: v2
appVersion: v0.30.0
description: GrafanaDatasource Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: openvizdev-grafanadatasource-editor
type: application
version: v0.30.0
