annotations:
  meta.x-helm.dev/editor: '{"group":"voyager.appscode.com","version":"v1beta1","resource":"certificates"}'
apiVersion: v2
appVersion: v0.30.0
description: Certificate Editor
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.14.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: voyagerappscodecom-certificate-editor
type: application
version: v0.30.0
