annotations:
  meta.x-helm.dev/editor: '{"group":"catalog.kubeware.dev","version":"v1alpha1","resource":"kafkabindings"}'
apiVersion: v2
appVersion: v0.30.0
description: KafkaBinding Editor
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: catalogkubewaredev-kafkabinding-editor
type: application
version: v0.30.0
