annotations:
  meta.x-helm.dev/editor: '{"group":"addons.kubestash.com","version":"v1alpha1","resource":"functions"}'
apiVersion: v2
appVersion: v0.30.0
description: Function Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: addonskubestashcom-function-editor
type: application
version: v0.30.0
