annotations:
  meta.x-helm.dev/editor: '{"group":"addon.open-cluster-management.io","version":"v1alpha1","resource":"managedclusteraddons"}'
apiVersion: v2
appVersion: v0.30.0
description: ManagedClusterAddOn Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: addonopenclustermanagementio-managedclusteraddon-editor
type: application
version: v0.30.0
