annotations:
  meta.x-helm.dev/editor: '{"group":"charts.x-helm.dev","version":"v1alpha1","resource":"chartpresets"}'
apiVersion: v2
appVersion: v0.30.0
description: ChartPreset Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: chartsxhelmdev-chartpreset-editor
type: application
version: v0.30.0
