annotations:
  meta.x-helm.dev/editor: '{"group":"events.k8s.io","version":"v1","resource":"events"}'
apiVersion: v2
appVersion: v0.30.0
description: Event Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: eventsk8sio-event-editor
type: application
version: v0.30.0
