annotations:
  meta.x-helm.dev/editor: '{"group":"proxy.open-cluster-management.io","version":"v1alpha1","resource":"managedproxyserviceresolvers"}'
apiVersion: v2
appVersion: v0.30.0
description: ManagedProxyServiceResolver Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: proxyopenclustermanagementio-managedproxyserviceresolver-editor
type: application
version: v0.30.0
