annotations:
  meta.x-helm.dev/editor: '{"group":"meta.appscode.com","version":"v1alpha1","resource":"resourcedescriptors"}'
apiVersion: v2
appVersion: v0.30.0
description: ResourceDescriptor Editor
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.14.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: metaappscodecom-resourcedescriptor-editor
type: application
version: v0.30.0
