annotations:
  meta.x-helm.dev/editor: '{"group":"secrets-store.csi.x-k8s.io","version":"v1","resource":"secretproviderclasses"}'
apiVersion: v2
appVersion: v0.30.0
description: SecretProviderClass Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: secretsstorecsixk8sio-secretproviderclass-editor
type: application
version: v0.30.0
