annotations:
  meta.x-helm.dev/editor: '{"group":"ui.k8s.appscode.com","version":"v1alpha1","resource":"featuresets"}'
  meta.x-helm.dev/resource-keys: helmToolkitFluxcdIoHelmRelease_cluster_auth_manager,helmToolkitFluxcdIoHelmRelease_cluster_gateway_manager,helmToolkitFluxcdIoHelmRelease_cluster_manager_hub,helmToolkitFluxcdIoHelmRelease_cluster_profile_manager,helmToolkitFluxcdIoHelmRelease_cluster_proxy_manager,helmToolkitFluxcdIoHelmRelease_fluxcd_manager,helmToolkitFluxcdIoHelmRelease_hub_cluster_robot,helmToolkitFluxcdIoHelmRelease_license_proxyserver_manager,helmToolkitFluxcdIoHelmRelease_managed_serviceaccount_manager
  meta.x-helm.dev/resources: "- group: helm.toolkit.fluxcd.io\n  kind: HelmRelease\n\
    \  version: v2\n"
apiVersion: v2
appVersion: v0.30.0
description: FeatureSet Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: uik8sappscodecom-featureset-ocm-hub-editor
type: application
version: v0.30.0
