annotations:
  meta.x-helm.dev/editor: '{"group":"storage.kubestash.com","version":"v1alpha1","resource":"backupstorages"}'
  meta.x-helm.dev/resource-keys: secret_storage_cred,storageKubestashComBackupStorage
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ storage.kubestash.com\n  kind: BackupStorage\n  version: v1alpha1\n"
apiVersion: v2
appVersion: v0.30.0
description: BackupStorage Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: storagekubestashcom-backupstorage-editor
type: application
version: v0.30.0
