annotations:
  meta.x-helm.dev/editor: '{"group":"stash.appscode.com","version":"v1alpha1","resource":"repositories"}'
  meta.x-helm.dev/resource-keys: secret_repo_cred,stashAppscodeComRepository
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ stash.appscode.com\n  kind: Repository\n  version: v1alpha1\n"
apiVersion: v2
appVersion: v0.30.0
description: Repository Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: stashappscodecom-repository-editor
type: application
version: v0.30.0
