annotations:
  meta.x-helm.dev/editor: '{"group":"ui.k8s.appscode.com","version":"v1alpha1","resource":"featuresets"}'
  meta.x-helm.dev/resource-keys: helmToolkitFluxcdIoHelmRelease_config_syncer,helmToolkitFluxcdIoHelmRelease_csi_secrets_store_provider_azure,helmToolkitFluxcdIoHelmRelease_external_secrets,helmToolkitFluxcdIoHelmRelease_kubevault,helmToolkitFluxcdIoHelmRelease_kubevault_opscenter,helmToolkitFluxcdIoHelmRelease_reloader,helmToolkitFluxcdIoHelmRelease_sealed_secrets,helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver,helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver_provider_aws,helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver_provider_gcp,helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver_provider_virtual_secrets,helmToolkitFluxcdIoHelmRelease_vault,helmToolkitFluxcdIoHelmRelease_vault_secrets_operator,helmToolkitFluxcdIoHelmRelease_virtual_secrets_server
  meta.x-helm.dev/resources: "- group: helm.toolkit.fluxcd.io\n  kind: HelmRelease\n\
    \  version: v2\n"
apiVersion: v2
appVersion: v0.30.0
description: FeatureSet Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: uik8sappscodecom-featureset-opscenter-secret-management-editor
type: application
version: v0.30.0
