step:
- elements:
  - label: To update Exporter Resource section click on Create OpsRequest
    type: label-element
  - init:
      type: func
      value: getOpsRequestUrl|scale-vertically
    label: Create OpsRequest
    schema: temp/properties/opsRequestUrl
    type: anchor
  - fullwidth: true
    init:
      type: func
      value: isValueExistInModel|/resources/kubedbComMemcached/spec/monitor
    label: Enable Monitoring
    schema: temp/properties/enableMonitoring
    type: switch
    watcher:
      func: onEnableMonitoringChange
      paths:
      - temp/properties/enableMonitoring
  - elements:
    - init:
        type: static
        value: prometheus.io/operator
      isHorizontal: true
      label: Select a Monitoring Method
      options:
      - description: Inject metric exporter sidecar and creates a ServiceMonitor
        text: Prometheus Operator
        value: prometheus.io/operator
      - description: Injects the metric exporter sidecar and let you customize ServiceMonitor
        text: Custom ServiceMonitor
        value: prometheus.io
      - description: Inject metric exporter sidecar and add Prometheus annotations
          to the stats Service
        text: Custom Scrapper
        value: prometheus.io/builtin
      schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/agent
      type: radio
      watcher:
        func: onAgentChange
        paths:
        - schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/agent
    - elements:
      - label: Scrapping Interval
        schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/prometheus/properties/serviceMonitor/properties/interval
        type: input
      if:
        name: isEqualToModelPathValue|prometheus.io/operator|/resources/kubedbComMemcached/spec/monitor/agent
        type: function
      label: ServiceMonitor Configuration
      showLabels: true
      type: block-layout
    - elements:
      - buttonClass: is-light is-outlined
        elements:
        - fullwidth: true
          label: Honor labels
          schema: honorLabels
          type: switch
        - label: Interval
          schema: interval
          type: input
          validation:
            type: required
        - label: Path
          schema: path
          type: input
          validation:
            type: required
        - label: Port
          schema: port
          type: input
          validation:
            type: required
        label: Endpoints
        schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/spec/properties/endpoints
        type: array-object-form
      - if:
          name: returnFalse
          type: function
        label: Match Namespaces
        loader: getResources|core|v1|namespaces
        multiple: true
        schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/spec/properties/namespaceSelector/properties/matchNames
        type: select
      - elements:
        - label: Labels
          schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/spec/properties/selector/properties/matchLabels
          type: object-item
        if:
          name: returnFalse
          type: function
        showLabels: false
        type: block-layout
      if:
        name: isEqualToModelPathValue|prometheus.io|/resources/kubedbComMemcached/spec/monitor/agent
        type: function
      label: Service Monitor
      showLabels: true
      type: block-layout
    - if:
        name: isEqualToModelPathValue|prometheus.io|/resources/kubedbComMemcached/spec/monitor/agent
        type: function
      label: Labels
      schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/metadata/properties/labels
      type: object-item
    - label: Exporter Configuration
      schema: ""
      type: label-element
    - fullwidth: true
      init:
        type: static
        value: true
      label: Customize Exporter Sidecar
      schema: temp/properties/customizeExporter
      type: switch
      watcher:
        func: onCustomizeExporterChange
        paths:
        - temp/properties/customizeExporter
    - elements:
      - if:
          name: returnFalse
          type: function
        label: Resources
        schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/resources
        type: machine-compare
      - label: Security Context
        schema: ""
        type: label-element
      - label: Run as User
        schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/securityContext/properties/runAsUser
        type: input
      - label: Run as Group
        schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/securityContext/properties/runAsGroup
        type: input
      - label: Port
        schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/port
        type: input
      - element:
          label: Args
          type: input
        init:
          type: static
          value:
          - --compatible-mode
        label: Args
        schema: schema/properties/resources/properties/kubedbComMemcached/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/args
        type: array-item-form
      - elements:
        - buttonClass: is-light is-outlined
          elements:
          - label: Name
            schema: name
            type: input
            validation:
              type: required
          - init:
              type: func
              value: setValueFrom
            label: Value From
            options:
            - text: Input
              value: input
            - text: Secret
              value: secret
            - text: ConfigMap
              value: configMap
            schema: temp/properties/valueFromType
            type: radio
            validation:
              type: required
            watcher:
              func: onValueFromChange
              paths:
              - temp/properties/valueFromType
          - if:
              name: isEqualToTemp|input
              type: function
            label: Value
            schema: value
            type: input
            validation:
              type: required
          - if:
              name: isEqualToTemp|configMap
              type: function
            label: ConfigMap Name
            loader:
              name: resourceNames|core|v1|configmaps
              watchPaths:
              - schema/metadata/release/namespace
            schema: valueFrom/properties/configMapKeyRef/properties/name
            type: select
            validation:
              type: required
          - if:
              name: isEqualToTemp|configMap
              type: function
            label: ConfigMap Key
            loader:
              name: getConfigMapKeys
              watchPaths:
              - schema/resources/kubedbComMemcached/spec/monitor/prometheus/exporter/env/dynamicIndex/valueFrom/configMapKeyRef/name
              - schema/metadata/release/namespace
            schema: valueFrom/properties/configMapKeyRef/properties/key
            type: select
          - if:
              name: isEqualToTemp|secret
              type: function
            label: Secret Name
            loader:
              name: getSecrets
              watchPaths:
              - schema/metadata/release/namespace
            schema: valueFrom/properties/secretKeyRef/properties/name
            type: select
            validation:
              type: required
          - if:
              name: isEqualToTemp|secret
              type: function
            label: Secret Key
            loader:
              name: getSecretKeys
              watchPaths:
              - schema/resources/kubedbComMemcached/spec/monitor/prometheus/exporter/env/dynamicIndex/valueFrom/secretKeyRef/name
              - schema/metadata/release/namespace
            schema: valueFrom/properties/secretKeyRef/properties/key
            type: select
          init:
            type: func
            value: initEnvArray
          label: Environment Variables
          schema: temp/properties/env
          type: array-object-form
          watcher:
            func: onEnvArrayChange
            paths:
            - temp/properties/env
        label: Metadata
        showLabels: false
        type: block-layout
      if:
        name: showCustomizeExporterSection
        type: function
      label: Customer Exporter Section
      showLabels: false
      type: block-layout
    if:
      name: showMonitoringSection
      type: function
    type: block-layout
  id: monitoring
  loader: initMonitoring
  type: single-step-form
- elements:
  - elements:
    - label: Name
      schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/metadata/properties/name
      type: input
    - if:
        name: isRancherManaged
        type: function
      label: Select Namespace
      loader: getNamespaces
      schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/metadata/properties/namespace
      type: select
      watcher:
        func: onNamespaceChange
        paths:
        - schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/metadata/properties/namespace
    - label: Select Db
      loader: getDbs
      refresh: true
      schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/databaseRef/properties/name
      type: select
      validation:
        type: required
      watcher:
        func: initMetadata
        paths:
        - schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/databaseRef/properties/name
    if:
      name: isConsole
      type: function
    type: block-layout
  - if:
      name: isConsole
      type: function
    label: Select Type
    options:
    - description: Scale your CPU Memory based on resource usage
      text: Compute
      value: compute
    - description: Expand your database size based on volume usage
      text: Storage
      value: storage
    schema: temp/properties/autoscalingType
    type: radio
    validation:
      type: required
    watcher:
      func: initMetadata
      paths:
      - temp/properties/autoscalingType
  - elements:
    - elements:
      - init:
          type: func
          value: setTrigger|autoscalingKubedbComMemcachedAutoscaler/spec/compute/memcached/trigger
        label: Trigger
        options:
        - text: "On"
          value: "On"
        - text: "Off"
          value: "Off"
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/trigger
        type: select
      - label: Pod LifeTime Threshold
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/podLifeTimeThreshold
        type: input
      - label: Resource Diff Percentage
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/resourceDiffPercentage
        type: threshold-input
      - elements:
        - header: Minimum Resource Limit
          if:
            name: hasAnnotations
            type: function
          init:
            type: func
            value: setAllowedMachine|min
          label: Min Allowed Profile
          loader:
            name: getMachines|min
            watchPaths:
            - temp/properties/topologyMachines
            - temp/properties/allowedMachine-max
          schema: temp/properties/allowedMachine-min
          type: machine-compare
          watcher:
            func: onMachineChange|memcached
            paths:
            - temp/properties/allowedMachine-min
        - elements:
          - label: Cpu
            schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/minAllowed/properties/cpu
            type: input-compare
          - label: Memory
            schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/minAllowed/properties/memory
            type: input-compare
          fixedBlock: true
          if:
            name: hasNoAnnotations
            type: function
          label: Min Allowed
          showLabels: true
          type: block-layout
        - header: Maximum Resource Limit
          if:
            name: hasAnnotations
            type: function
          init:
            type: func
            value: setAllowedMachine|max
          label: Max Allowed Profile
          loader:
            name: getMachines|max
            watchPaths:
            - temp/properties/topologyMachines
            - temp/properties/allowedMachine-min
          schema: temp/properties/allowedMachine-max
          type: machine-compare
          watcher:
            func: onMachineChange|memcached
            paths:
            - temp/properties/allowedMachine-max
        - elements:
          - label: Cpu
            schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/maxAllowed/properties/cpu
            type: input-compare
          - label: Memory
            schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/maxAllowed/properties/memory
            type: input-compare
          fixedBlock: true
          if:
            name: hasNoAnnotations
            type: function
          label: Max Allowed
          showLabels: true
          type: block-layout
        showLabels: false
        type: block-layout
      - label: Controlled Resources
        loader: setControlledResources|memcached
        multiple: true
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/memcached/properties/controlledResources
        type: select
      label: Memcached
      showLabels: true
      type: block-layout
    - elements:
      - label: Select Node Topology
        loader: fetchNodeTopology
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/nodeTopology/properties/name
        type: select
      - if:
          name: isNodeTopologySelected
          type: function
        label: ScaleUp Diff Percentage
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/nodeTopology/properties/scaleUpDiffPercentage
        type: threshold-input
      - if:
          name: isNodeTopologySelected
          type: function
        label: ScaleDown Diff Percentage
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/compute/properties/nodeTopology/properties/scaleDownDiffPercentage
        type: threshold-input
      if:
        name: hasNoAnnotations
        type: function
      label: Node Topology
      showLabels: true
      type: block-layout
    - elements:
      - label: Timeout
        options:
        - text: 5 minutes
          value: 5m0s
        - text: 10 minutes
          value: 10m0s
        - text: 30 minutes
          value: 30m0s
        - text: 1 hour
          value: 1h0m
        - text: 2 hours
          value: 2h0m
        - text: 5 hours
          value: 5h0m
        - text: 10 hours
          value: 10h0m
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/opsRequestOptions/properties/timeout
        type: select
      - init:
          type: func
          value: setApplyToIfReady
        label: Apply
        options:
        - text: IfReady (OpsRequest will be applied if database is ready)
          value: IfReady
        - text: Always (OpsRequest will always be applied)
          value: Always
        schema: schema/properties/resources/properties/autoscalingKubedbComMemcachedAutoscaler/properties/spec/properties/opsRequestOptions/properties/apply
        type: radio
      if:
        name: showOpsRequestOptions
        type: function
      label: Ops Request Options
      showLabels: true
      type: block-layout
    loader: fetchTopologyMachines
    showLabels: false
    type: block-layout
  id: compute-autoscaler
  loader: getDbDetails
  type: single-step-form
type: multi-step-form
