step:
- type: single-step-form
  elements:
  - loader: getDatabases|core.k8s.appscode.com|v1alpha1|genericresources
    if: 
      name: isConsole
      type: function
    label: Select Database
    refresh: true
    validation:
      type: required
    schema: temp/properties/database
    sortable: true
    type: select
  - watcher:
      func: setRoleName
      paths:
        - schema/properties/spec/properties/secretEngineRef/properties/name
    label: Name
    validation:
      type: required
    schema: schema/properties/metadata/properties/name
    type: input
  - init:
      value: getDbNamespace
      type: func
    disable: true
    if:
      name: isDbSelected
      type: function
    label: Namespace
    schema: schema/properties/metadata/properties/namespace
    type: input
  - loader: getEngines|engine.kubevault.com|v1alpha1|secretengines
    if:
      name: isDbSelected
      type: function
    label: Select SecretEngine
    refresh: true
    validation:
      type: required
    schema: schema/properties/spec/properties/secretEngineRef/properties/name
    type: select
  - label: Default TTL
    schema: schema/properties/spec/properties/defaultTTL
    type: input
  - label: Max TTL
    schema: schema/properties/spec/properties/maxTTL
    type: input
  - type: array-item-form
    element:
      label: Statement
      type: input
    label: Creation Statement
    schema: schema/properties/spec/properties/creationStatements
  - type: array-item-form
    element:
      label: Statement
      type: input
    label: Revocation Statement
    schema: schema/properties/spec/properties/revocationStatements
type: multi-step-form
