annotations:
  meta.x-helm.dev/editor: '{"group":"node.k8s.appscode.com","version":"v1alpha1","resource":"nodetopologies"}'
apiVersion: v2
appVersion: v0.30.0
description: NodeTopology Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: nodek8sappscodecom-nodetopology-editor
type: application
version: v0.30.0
