annotations:
  meta.x-helm.dev/editor: '{"group":"snapshot.storage.k8s.io","version":"v1","resource":"volumesnapshotcontents"}'
apiVersion: v2
appVersion: v0.30.0
description: VolumeSnapshotContent Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: snapshotstoragek8sio-volumesnapshotcontent-editor
type: application
version: v0.30.0
