annotations:
  meta.x-helm.dev/editor: '{"group":"kubedb.com","version":"v1","resource":"redissentinels"}'
  meta.x-helm.dev/resource-keys: certManagerIoIssuer_redis_ca,gitopsKubedbComRedisSentinel,kubedbComRedisSentinel,monitoringCoreosComServiceMonitor_redis,secret_auth
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ cert-manager.io\n  kind: Issuer\n  version: v1\n- group: gitops.kubedb.com\n\
    \  kind: RedisSentinel\n  version: v1alpha1\n- group: kubedb.com\n  kind: RedisSentinel\n\
    \  version: v1\n- group: monitoring.coreos.com\n  kind: ServiceMonitor\n  version:\
    \ v1\n"
apiVersion: v2
appVersion: v0.30.0
description: RedisSentinel Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedbcom-redissentinel-editor
type: application
version: v0.30.0
