annotations:
  meta.x-helm.dev/editor: '{"group":"kustomize.toolkit.fluxcd.io","version":"v1","resource":"kustomizations"}'
apiVersion: v2
appVersion: v0.30.0
description: Kustomization Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kustomizetoolkitfluxcdio-kustomization-editor
type: application
version: v0.30.0
