annotations:
  meta.x-helm.dev/editor: '{"group":"kubedb.com","version":"v1alpha2","resource":"singlestores"}'
  meta.x-helm.dev/form-keys: monitoringCoreosComPrometheusRule
  meta.x-helm.dev/resource-keys: autoscalingKubedbComSinglestoreAutoscaler,catalogAppscodeComSinglestoreBinding,certManagerIoIssuer_ca,coreKubestashComBackupBlueprint,coreKubestashComBackupConfiguration,coreKubestashComRestoreSession,gitopsKubedbComSinglestore,kubedbComSinglestore,monitoringCoreosComServiceMonitor,secret_auth,secret_config
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ autoscaling.kubedb.com\n  kind: SinglestoreAutoscaler\n  version: v1alpha1\n\
    - group: catalog.appscode.com\n  kind: SinglestoreBinding\n  version: v1alpha1\n\
    - group: cert-manager.io\n  kind: Issuer\n  version: v1\n- group: core.kubestash.com\n\
    \  kind: BackupBlueprint\n  version: v1alpha1\n- group: core.kubestash.com\n \
    \ kind: BackupConfiguration\n  version: v1alpha1\n- group: core.kubestash.com\n\
    \  kind: RestoreSession\n  version: v1alpha1\n- group: gitops.kubedb.com\n  kind:\
    \ Singlestore\n  version: v1alpha1\n- group: kubedb.com\n  kind: Singlestore\n\
    \  version: v1alpha2\n- group: monitoring.coreos.com\n  kind: PrometheusRule\n\
    \  version: v1\n- group: monitoring.coreos.com\n  kind: ServiceMonitor\n  version:\
    \ v1\n"
apiVersion: v2
appVersion: v0.30.0
description: Singlestore Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedbcom-singlestore-editor
type: application
version: v0.30.0
