annotations:
  meta.x-helm.dev/editor: '{"group":"cluster.open-cluster-management.io","version":"v1beta2","resource":"managedclustersetbindings"}'
apiVersion: v2
appVersion: v0.30.0
description: ManagedClusterSetBinding Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: clusteropenclustermanagementio-managedclustersetbinding-editor
type: application
version: v0.30.0
