annotations:
  meta.x-helm.dev/editor: '{"group":"project.openshift.io","version":"v1","resource":"projects"}'
apiVersion: v2
appVersion: v0.30.0
description: Project Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: projectopenshiftio-project-editor
type: application
version: v0.30.0
