annotations:
  meta.x-helm.dev/editor: '{"group":"ec2.aws.kubedb.com","version":"v1alpha1","resource":"subnets"}'
apiVersion: v2
appVersion: v0.30.0
description: Subnet Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: ec2awskubedbcom-subnet-editor
type: application
version: v0.30.0
