annotations:
  meta.x-helm.dev/editor: '{"group":"core.kubestash.com","version":"v1alpha1","resource":"restoresessions"}'
  meta.x-helm.dev/resource-keys: coreKubestashComRestoreSession
  meta.x-helm.dev/resources: "- group: core.kubestash.com\n  kind: RestoreSession\n\
    \  version: v1alpha1\n"
apiVersion: v2
appVersion: v0.30.0
description: RestoreSession Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: corekubestashcom-restoresession-editor
type: application
version: v0.30.0
