annotations:
  meta.x-helm.dev/editor: '{"group":"mutations.gatekeeper.sh","version":"v1","resource":"assign"}'
apiVersion: v2
appVersion: v0.30.0
description: Assign Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: mutationsgatekeepersh-assign-editor
type: application
version: v0.30.0
