annotations:
  meta.x-helm.dev/editor: '{"group":"authentication.k8s.io","version":"v1","resource":"tokenrequests"}'
apiVersion: v2
appVersion: v0.30.0
description: TokenRequest Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: authenticationk8sio-tokenrequest-editor
type: application
version: v0.30.0
