apiVersion: v2
name: kubevaultcom-vaultserver-editor-options
description: VaultServer Editor UI Options
type: application
version: v0.30.0
appVersion: v0.30.0
maintainers:
- name: appscode
  email: support@appscode.com
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/kubevault/kubevault-community-icon.png
