annotations:
  meta.x-helm.dev/editor: '{"group":"ipam.cluster.x-k8s.io","version":"v1beta1","resource":"ipaddresses"}'
apiVersion: v2
appVersion: v0.30.0
description: IPAddress Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: ipamclusterxk8sio-ipaddress-editor
type: application
version: v0.30.0
