steps:
- form:
    discriminator:
      isResourceLoaded:
        default: false
        type: boolean
    elements:
    - computed: setReleaseNameAndNamespaceAndInitializeValues
      if: returnFalse
      type: input
    - discriminator:
        enabledFeatures:
          type: array
      elements:
      - computed: getFeatureSetDescription
        customClass: mb-20
        label:
          isSubsection: true
        type: label-element
      - computed: getEnabledFeatures
        fetch: fetchFeatureSetOptions
        hasDescription: true
        individualItemDisabilityCheck: disableFeatures
        onChange: onEnabledFeaturesChange
        schema:
          $ref: discriminator#/properties/enabledFeatures
        type: checkbox
      - computed: checkIsResourceLoaded
        if: hideThisElement
        type: input
      - alertInfo:
          show: true
          type: info
        label:
          text: 'Note: Enabling a feature auto enables any prerequisite features'
        type: label-element
      - if: checkIsOtelStackEnabled
        fetch: fetchMonitoringClusterOptions
        onChange: onMonitoringClusterChange
        required: true
        label:
          text: Select Monitoring Cluster
        schema:
          $ref: discriminator#/properties/monitoringClusterName
        type: select
      type: single-step-form
    type: single-step-form
  id: opscenter-monitoring
  title: steps.0.label
type: multi-step-form
