elements:
  - customClass: mb-10
    label:
      hasLine: true
      text: labels.resources
    type: label-element
  - elements:
      - label:
          hasLine: true
          isSubsection: true
          text: labels.request
        type: label-element
      - label:
          text: labels.cpu
        schema:
          $ref: schema#/properties/requests/properties/cpu
        type: input
      - label:
          text: labels.memory
        schema:
          $ref: schema#/properties/requests/properties/memory
        type: input
    schema:
      $ref: schema#/properties/requests
    type: single-step-form
  - elements:
      - label:
          hasLine: true
          isSubsection: true
          text: labels.limit
        type: label-element
      - label:
          text: labels.cpu
        schema:
          $ref: schema#/properties/limits/properties/cpu
        type: input
      - label:
          text: labels.memory
        schema:
          $ref: schema#/properties/limits/properties/memory
        type: input
    schema:
      $ref: schema#/properties/limits
    type: single-step-form
schema:
  $ref: schema#/
type: single-step-form
