annotations:
  meta.x-helm.dev/editor: '{"group":"discovery.k8s.io","version":"v1","resource":"endpointslices"}'
apiVersion: v2
appVersion: v0.30.0
description: EndpointSlice Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: discoveryk8sio-endpointslice-editor
type: application
version: v0.30.0
