annotations:
  meta.x-helm.dev/editor: '{"group":"gateway.envoyproxy.io","version":"v1alpha1","resource":"envoyproxies"}'
apiVersion: v2
appVersion: v0.30.0
description: EnvoyProxy Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: gatewayenvoyproxyio-envoyproxy-editor
type: application
version: v0.30.0
