annotations:
  meta.x-helm.dev/editor: '{"group":"apiextensions.crossplane.io","version":"v1","resource":"compositionrevisions"}'
apiVersion: v2
appVersion: v0.30.0
description: CompositionRevision Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: apiextensionscrossplaneio-compositionrevision-editor
type: application
version: v0.30.0
