annotations:
  meta.x-helm.dev/editor: '{"group":"controlplane.cluster.x-k8s.io","version":"v1beta2","resource":"rosacontrolplanes"}'
apiVersion: v2
appVersion: v0.30.0
description: ROSAControlPlane Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: controlplaneclusterxk8sio-rosacontrolplane-editor
type: application
version: v0.30.0
