annotations:
  meta.x-helm.dev/editor: '{"group":"admissionregistration.k8s.io","version":"v1","resource":"validatingwebhookconfigurations"}'
apiVersion: v2
appVersion: v0.30.0
description: ValidatingWebhookConfiguration Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: admissionregistrationk8sio-validatingwebhookconfiguration-editor
type: application
version: v0.30.0
