annotations:
  meta.x-helm.dev/editor: '{"group":"infrastructure.cluster.x-k8s.io","version":"v1beta1","resource":"azuremachines"}'
apiVersion: v2
appVersion: v0.30.0
description: AzureMachine Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: infrastructureclusterxk8sio-azuremachine-editor
type: application
version: v0.30.0
