annotations:
  meta.x-helm.dev/editor: '{"group":"ui.k8s.appscode.com","version":"v1alpha1","resource":"featuresets"}'
  meta.x-helm.dev/resource-keys: helmToolkitFluxcdIoHelmRelease_keda,helmToolkitFluxcdIoHelmRelease_keda_add_ons_http,helmToolkitFluxcdIoHelmRelease_opencost,helmToolkitFluxcdIoHelmRelease_opencost_grafana_dashboards
  meta.x-helm.dev/resources: "- group: helm.toolkit.fluxcd.io\n  kind: HelmRelease\n\
    \  version: v2\n"
apiVersion: v2
appVersion: v0.30.0
description: FeatureSet Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: uik8sappscodecom-featureset-opscenter-cost-editor
type: application
version: v0.30.0
