apiVersion: v2
name: storagekubestashcom-repository-editor-options
description: Stash Repository Editor UI Options
type: application
version: v0.30.0
appVersion: v0.30.0
maintainers:
- name: appscode
  email: support@appscode.com
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-community-icon.png
