annotations:
  meta.x-helm.dev/editor: '{"group":"rbac.authorization.k8s.io","version":"v1","resource":"rolebindings"}'
apiVersion: v2
appVersion: v0.30.0
description: RoleBinding Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: rbacauthorizationk8sio-rolebinding-editor
type: application
version: v0.30.0
