annotations:
  meta.x-helm.dev/editor: '{"group":"networking.k8s.io","version":"v1","resource":"networkpolicies"}'
apiVersion: v2
appVersion: v0.30.0
description: NetworkPolicy Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: networkingk8sio-networkpolicy-editor
type: application
version: v0.30.0
