annotations:
  meta.x-helm.dev/editor: '{"group":"grafana.searchlight.dev","version":"v1alpha1","resource":"datasources"}'
apiVersion: v2
appVersion: v0.30.0
description: Datasource Editor
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.14.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: grafanasearchlightdev-datasource-editor
type: application
version: v0.30.0
