annotations:
  meta.x-helm.dev/editor: '{"group":"ui.k8s.appscode.com","version":"v1alpha1","resource":"featuresets"}'
  meta.x-helm.dev/resource-keys: helmToolkitFluxcdIoHelmRelease_grafana_operator,helmToolkitFluxcdIoHelmRelease_kube_grafana_dashboards,helmToolkitFluxcdIoHelmRelease_kube_prometheus_stack,helmToolkitFluxcdIoHelmRelease_metrics_server,helmToolkitFluxcdIoHelmRelease_monitoring_operator,helmToolkitFluxcdIoHelmRelease_panopticon,helmToolkitFluxcdIoHelmRelease_prometheus_adapter
  meta.x-helm.dev/resources: "- group: helm.toolkit.fluxcd.io\n  kind: HelmRelease\n\
    \  version: v2beta2\n"
apiVersion: v2
appVersion: v0.30.0
description: FeatureSet Editor
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: uik8sappscodecom-featureset-opscenter-monitoring-editor
type: application
version: v0.30.0
