apiVersion: v2
name: uibytebuildersdev-component-kubedb-ui-presets
description: kubedb-ui preset reusable preset chart
type: library
version: v0.30.0
appVersion: v0.30.0
maintainers:
- name: appscode
  email: support@appscode.com
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-community-icon.png
