annotations:
  meta.x-helm.dev/editor: '{"group":"kubedb.com","version":"v1","resource":"perconaxtradbs"}'
  meta.x-helm.dev/form-keys: monitoringCoreosComPrometheusRule
  meta.x-helm.dev/resource-keys: autoscalingKubedbComPerconaXtraDBAutoscaler,catalogAppscodeComPerconaXtraDBBinding,certManagerIoIssuer_ca,gitopsKubedbComPerconaXtraDB,kubedbComPerconaXtraDB,monitoringCoreosComServiceMonitor,secret_auth,secret_config
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ autoscaling.kubedb.com\n  kind: PerconaXtraDBAutoscaler\n  version: v1alpha1\n\
    - group: catalog.appscode.com\n  kind: PerconaXtraDBBinding\n  version: v1alpha1\n\
    - group: cert-manager.io\n  kind: Issuer\n  version: v1\n- group: gitops.kubedb.com\n\
    \  kind: PerconaXtraDB\n  version: v1alpha1\n- group: kubedb.com\n  kind: PerconaXtraDB\n\
    \  version: v1\n- group: monitoring.coreos.com\n  kind: PrometheusRule\n  version:\
    \ v1\n- group: monitoring.coreos.com\n  kind: ServiceMonitor\n  version: v1\n"
apiVersion: v2
appVersion: v0.30.0
description: PerconaXtraDB Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedbcom-perconaxtradb-editor
type: application
version: v0.30.0
