annotations:
  meta.x-helm.dev/editor: '{"group":"runtime.cluster.x-k8s.io","version":"v1alpha1","resource":"extensionconfigs"}'
apiVersion: v2
appVersion: v0.30.0
description: ExtensionConfig Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: runtimeclusterxk8sio-extensionconfig-editor
type: application
version: v0.30.0
