annotations:
  meta.x-helm.dev/editor: '{"group":"karpenter.k8s.aws","version":"v1beta1","resource":"ec2nodeclasses"}'
apiVersion: v2
appVersion: v0.30.0
description: EC2NodeClass Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: karpenterk8saws-ec2nodeclass-editor
type: application
version: v0.30.0
