annotations:
  meta.x-helm.dev/editor: '{"group":"storage.k8s.io","version":"v1beta1","resource":"csistoragecapacities"}'
apiVersion: v2
appVersion: v0.30.0
description: CSIStorageCapacity Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: storagek8sio-csistoragecapacity-editor
type: application
version: v0.30.0
