annotations:
  meta.x-helm.dev/editor: '{"group":"kubedb.com","version":"v1","resource":"kafkas"}'
  meta.x-helm.dev/resource-keys: autoscalingKubedbComKafkaAutoscaler,catalogAppscodeComKafkaBinding,gitopsKubedbComKafka,kubedbComKafka,monitoringCoreosComServiceMonitor,secret_admin_cred
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ autoscaling.kubedb.com\n  kind: KafkaAutoscaler\n  version: v1alpha1\n- group:\
    \ catalog.appscode.com\n  kind: KafkaBinding\n  version: v1alpha1\n- group: gitops.kubedb.com\n\
    \  kind: Kafka\n  version: v1alpha1\n- group: kubedb.com\n  kind: Kafka\n  version:\
    \ v1\n- group: monitoring.coreos.com\n  kind: ServiceMonitor\n  version: v1\n"
apiVersion: v2
appVersion: v0.30.0
description: Kafka Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedbcom-kafka-editor
type: application
version: v0.30.0
