elements:
- isArray: true
  keys:
    label:
      text: labels.labels.key
  label:
    text: labels.labels.label
  schema:
    $ref: schema#/properties/matchLabels
  type: key-value-input-form
  values:
    label:
      text: labels.labels.value
    schema:
      $ref: schema#/properties/matchLabels/additionalProperties
    type: input
- alias: reusable_selector_match_expressions
  chart:
    name: uibytebuildersdev-component-match-expressions
    version: v0.30.0
  customClass: mb-10
  moduleResolver: fetchJsons
  schema:
    $ref: schema#/properties/matchExpressions
  type: reusable-element
schema:
  $ref: schema#/
type: single-step-form
