annotations:
  meta.x-helm.dev/editor: '{"group":"core.kubestash.com","version":"v1alpha1","resource":"backupsessions"}'
  meta.x-helm.dev/resource-keys: coreKubestashComBackupSession
  meta.x-helm.dev/resources: "- group: core.kubestash.com\n  kind: BackupSession\n\
    \  version: v1alpha1\n"
apiVersion: v2
appVersion: v0.30.0
description: BackupSession Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: corekubestashcom-backupsession-editor
type: application
version: v0.30.0
