annotations:
  meta.x-helm.dev/editor: '{"group":"kubedb.com","version":"v1","resource":"elasticsearches"}'
  meta.x-helm.dev/form-keys: monitoringCoreosComPrometheusRule
  meta.x-helm.dev/resource-keys: autoscalingKubedbComElasticsearchAutoscaler,catalogAppscodeComElasticsearchBinding,certManagerIoIssuer_ca,coreKubestashComBackupBlueprint,coreKubestashComBackupConfiguration,coreKubestashComRestoreSession,gitopsKubedbComElasticsearch,kubedbComElasticsearch,monitoringCoreosComServiceMonitor,secret_admin_cred,secret_elastic_cred,secret_encryption_secret,secret_init_repo_cred,secret_kibanaro_cred,secret_kibanaserver_cred,secret_logstash_cred,secret_metrics_exporter_cred,secret_readall_cred,secret_repo_cred,secret_secure_config,secret_snapshotrestore_cred,secret_user_config,stashAppscodeComBackupConfiguration,stashAppscodeComRepository_init_repo,stashAppscodeComRepository_repo,stashAppscodeComRestoreSession_init
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ autoscaling.kubedb.com\n  kind: ElasticsearchAutoscaler\n  version: v1alpha1\n\
    - group: catalog.appscode.com\n  kind: ElasticsearchBinding\n  version: v1alpha1\n\
    - group: cert-manager.io\n  kind: Issuer\n  version: v1\n- group: core.kubestash.com\n\
    \  kind: BackupBlueprint\n  version: v1alpha1\n- group: core.kubestash.com\n \
    \ kind: BackupConfiguration\n  version: v1alpha1\n- group: core.kubestash.com\n\
    \  kind: RestoreSession\n  version: v1alpha1\n- group: gitops.kubedb.com\n  kind:\
    \ Elasticsearch\n  version: v1alpha1\n- group: kubedb.com\n  kind: Elasticsearch\n\
    \  version: v1\n- group: monitoring.coreos.com\n  kind: PrometheusRule\n  version:\
    \ v1\n- group: monitoring.coreos.com\n  kind: ServiceMonitor\n  version: v1\n\
    - group: stash.appscode.com\n  kind: BackupConfiguration\n  version: v1beta1\n\
    - group: stash.appscode.com\n  kind: Repository\n  version: v1alpha1\n- group:\
    \ stash.appscode.com\n  kind: RestoreSession\n  version: v1beta1\n"
apiVersion: v2
appVersion: v0.30.0
description: Elasticsearch Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedbcom-elasticsearch-editor
type: application
version: v0.30.0
