annotations:
  meta.x-helm.dev/editor: '{"group":"ui.k8s.appscode.com","version":"v1alpha1","resource":"featuresets"}'
  meta.x-helm.dev/resource-keys: helmToolkitFluxcdIoHelmRelease_aws_credential_manager,helmToolkitFluxcdIoHelmRelease_aws_ebs_csi_driver,helmToolkitFluxcdIoHelmRelease_aws_load_balancer_controller,helmToolkitFluxcdIoHelmRelease_capa_vpc_peering_operator,helmToolkitFluxcdIoHelmRelease_cluster_autoscaler
  meta.x-helm.dev/resources: "- group: helm.toolkit.fluxcd.io\n  kind: HelmRelease\n\
    \  version: v2\n"
apiVersion: v2
appVersion: v0.30.0
description: FeatureSet Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: uik8sappscodecom-featureset-capi-capa-editor
type: application
version: v0.30.0
