annotations:
  meta.x-helm.dev/editor: '{"group":"kubevault.com","version":"v1alpha1","resource":"vaultservers"}'
  meta.x-helm.dev/form-keys: monitoringCoreosComPrometheusRule
  meta.x-helm.dev/resource-keys: kubevaultComVaultServer,monitoringCoreosComServiceMonitor,secret_backend_creds,secret_backend_tls,secret_config,secret_repo_cred,secret_unsealer_creds,stashAppscodeComBackupConfiguration,stashAppscodeComRepository_repo
  meta.x-helm.dev/resources: "- group: \"\"\n  kind: Secret\n  version: v1\n- group:\
    \ kubevault.com\n  kind: VaultServer\n  version: v1alpha2\n- group: monitoring.coreos.com\n\
    \  kind: PrometheusRule\n  version: v1\n- group: monitoring.coreos.com\n  kind:\
    \ ServiceMonitor\n  version: v1\n- group: stash.appscode.com\n  kind: BackupConfiguration\n\
    \  version: v1beta1\n- group: stash.appscode.com\n  kind: Repository\n  version:\
    \ v1alpha1\n"
apiVersion: v2
appVersion: v0.30.0
description: VaultServer Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubevaultcom-vaultserver-editor
type: application
version: v0.30.0
