annotations:
  meta.x-helm.dev/editor: '{"group":"autoscaling.kubedb.com","version":"v1alpha1","resource":"verticalautoscalercheckpoints"}'
apiVersion: v2
appVersion: v0.30.0
description: VerticalAutoscalerCheckpoint Editor
home: https://byte.builders
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.14.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: autoscalingkubedbcom-verticalautoscalercheckpoint-editor
type: application
version: v0.30.0
